using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Web.UI;



[assembly: AssemblyTitle("XIOT")]
[assembly: AssemblyDescription("Data Aquarium Framework application library")]
[assembly: AssemblyCompany("XIOT")]
[assembly: AssemblyProduct("XIOT Aquarium in the Box")]
[assembly: AssemblyCopyright("Copyright © XIOT 2012")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: WebResource("XIOT.Scripts.Web.DataView.js", "text/javascript")]
[assembly: WebResource("XIOT.Scripts.Web.DataViewResources.js", "text/javascript")]
[assembly: WebResource("XIOT.Scripts.Web.DataViewResources.en_US.js", "text/javascript")]
[assembly: WebResource("XIOT.Scripts.Web.Menu.js", "text/javascript")]
[assembly: WebResource("XIOT.Theme.Aquarium.css", "text/css", PerformSubstitution=true)]
[assembly: WebResource("XIOT.Theme.Acrobat.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ActionBarBg.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ActionBarDiv.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ActionGroupBg.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.AddBookmark.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.AdvancedSearch.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ArrowBkg.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Attach.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Attention.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.BACK.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Calendar.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.CheckMark.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.CheckMark2.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.CheckMarkLarge.GIF", "image/GIF")]
[assembly: WebResource("XIOT.Theme.Close.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.DataSheet.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Delete.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.DropArrow.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Edit.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.EditMode.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Erase.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Excel.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.EXCLAIM.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ExportCsv.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ExportRowset.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ExportRss.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Filter.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.FilterOff.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.FilterOffDisabled.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.FORWARD.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.HeaderBg.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ICONGO.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Import.png", "image/png")]
[assembly: WebResource("XIOT.Theme.Information.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Maximize.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.MenuBg.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.MenuBgLarge.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Minimize.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.MultiPage.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Navigate.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.NavStrip.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.New.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.NewLarge.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ObjectRef.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Paste.png", "image/png")]
[assembly: WebResource("XIOT.Theme.PopupArrow.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Print.png", "image/png")]
[assembly: WebResource("XIOT.Theme.QuickFind.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Refresh.png", "image/png")]
[assembly: WebResource("XIOT.Theme.Save.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.SaveLarge.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Search.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Search.png", "image/png")]
[assembly: WebResource("XIOT.Theme.SearchPlusMinus.png", "image/png")]
[assembly: WebResource("XIOT.Theme.SettingsGraphic.jpg", "image/jpg")]
[assembly: WebResource("XIOT.Theme.SortAZ.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.SortDown.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.SortUp.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.SortZA.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.StatusBar.png", "image/png")]
[assembly: WebResource("XIOT.Theme.TabsActiveTab.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.TabsBar.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.TabsInactiveTab.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.TabsSelectedTab.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.TreeControls.png", "image/png")]
[assembly: WebResource("XIOT.Theme.Undo.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.ViewNameBg.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Wait.gif", "image/gif")]
[assembly: WebResource("XIOT.Theme.Word.gif", "image/gif")]
